apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-south1-docker.pkg.dev/project-eefd8d29-a5e4-42f7-964/task-repo/task-frontend:0535a63a310f322dfbedde1a6057359f5ef8562b
          ports:
            - containerPort: 80
