name: Build and Deploy to GKE

on:
  push:
    branches: [master]

permissions:
  contents: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth (Workload Identity)
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/752687754332/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@project-eefd8d29-a5e4-42f7-964.iam.gserviceaccount.com"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push Frontend
        run: |
          docker build -t asia-south1-docker.pkg.dev/project-eefd8d29-a5e4-42f7-964/task-repo/task-frontend:${{ github.sha }} ./frontend
          docker push asia-south1-docker.pkg.dev/project-eefd8d29-a5e4-42f7-964/task-repo/task-frontend:${{ github.sha }}

      - name: Build and Push Backend
        run: |
          docker build -t asia-south1-docker.pkg.dev/project-eefd8d29-a5e4-42f7-964/task-repo/task-backend:${{ github.sha }} ./backend
          docker push asia-south1-docker.pkg.dev/project-eefd8d29-a5e4-42f7-964/task-repo/task-backend:${{ github.sha }}

      - name: Update Image Tags in YAML
        run: |
          sed -i "s|task-frontend:.*|task-frontend:${{ github.sha }}|g" frontend-deployment.yaml
          sed -i "s|task-backend:.*|task-backend:${{ github.sha }}|g" backend-deployment.yaml

      - name: Commit and Push updated YAMLs
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add frontend-deployment.yaml backend-deployment.yaml
          git commit -m "ci: update image tags to ${{ github.sha }}"
          git push